config/routes.rb
Rails.application.routes.draw do

  root to: 'toppages#index'
  delete 'logout', to: 'users#destroy'
  
  resources :users, only: [:show, :new ,:create ,:destroy]
  
  resources :sessions, only: [:create, :destroy]

  resources :chems, only: [:new, :create, :edit, :destroy] do
     resources :enterings, only: [:new, :create]
  end

  resources :historys, only: [:show]

  resources :chems, only: [:new, :create, :edit, :destroy] do
     resources :dispatchings, only: [:new, :create]
  end

  #resources :dispatchings, only: [:new, :create]
  

  #resources :enterings, only: [:new, :create]

  resources :serchings, only: [:show]






  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chem.rb
class Chem < ApplicationRecord
  validates :chemical_name, presence: true, length: { maximum: 20}, uniqueness: { case_sensitive: false, scope: :user_id }

  has_many :enterings, :dependent => :destroy
  has_many :dispatchings, :dependent => :destroy
  belongs_to :user
end

app/models/dispatching.rb
class Dispatching < ApplicationRecord
  validates :dispatching_number,numericality: { only_integer: true, greater_than_or_equal_to: 1 }, presence: true, length: { maximum: 10 }
  validates :dispatching_person, presence: true, length: { maximum: 10 }
  belongs_to :chem
end

app/models/entering.rb
class Entering < ApplicationRecord
  validates :entering_number, numericality: { only_integer: true, greater_than_or_equal_to: 1 },presence: true, length: { maximum: 10 }
  validates :entering_person, presence: true, length: { maximum: 10 }
  belongs_to :chem

end

app/models/user.rb
class User < ApplicationRecord
  validates :company_name, presence: true, length: { maximum: 20 }
  validates :login_id, presence: true, length: { maximum: 10 }
  validates :password, presence: true, length: { maximum: 10 }
  has_secure_password
  has_many :chems
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionHelper

  private

  def require_user_logged_in
    unless logged_in?
      redirect_to root_url
    end
  end
end

app/controllers/chems_controller.rb
class ChemsController < ApplicationController
  before_action :require_user_logged_in
  include SessionHelper
  
  def new
    @chem = Chem.new
  end
  
  def create
    @chem = current_user.chems.build(chem_params)
    if @chem.save
      flash[:success] = '品名を登録しました。'
      redirect_to current_user
    else
      flash.now[:danger] = '品名の登録に失敗しました。'
      render :new
    end
  end
  
  def edit
    @chem = Chem.find(params[:id])
  end
  
  def destroy
    @chem = Chem.find(params[:id])
    @chem.destroy
    flash[:success] = @chem.chemical_name + 'を削除しました。'
    redirect_to current_user
  end
  
 private

  def chem_params
    params.require(:chem).permit(:chemical_name)
  end
  
end

app/controllers/dispatchings_controller.rb
class DispatchingsController < ApplicationController
  before_action :require_user_logged_in
  include SessionHelper

  def new
    @chem = Chem.find(params[:chem_id])
    @dispatching = Dispatching.new
    
  end
  
  def create
    @chem = Chem.find(params[:chem_id])
    @dispatching = @chem.dispatchings.build(dispatching_params)
    
    if @dispatching.dispatching_number.nil?
     flash[:danger] = '出庫数を入力して下さい。'
     redirect_to new_chem_dispatching_path
     
    elsif @dispatching.dispatching_person.empty?
     flash[:danger] = '出庫者を入力して下さい。'
     redirect_to new_chem_dispatching_path
  
    elsif @dispatching.dispatching_number > (@chem.enterings.pluck(:entering_number).sum - @chem.dispatchings.pluck(:dispatching_number).sum)
      flash[:danger] = '在庫数より多い数量を出庫できません。'
      redirect_to new_chem_dispatching_path
      
    elsif @dispatching.save
      flash[:success] = '出庫に成功しました。'
      redirect_to current_user
    
    else
      flash[:danger] = '出庫に失敗しました。'
      redirect_to new_chem_dispatching_path
    end
  end
  


 private

  def dispatching_params
    params.require(:dispatching).permit(:dispatching_number, :dispatching_person)
  end
  
end

app/controllers/enterings_controller.rb
class EnteringsController < ApplicationController
  before_action :require_user_logged_in
  include SessionHelper

  def new
    @chem = Chem.find(params[:chem_id])
    @entering = Entering.new
    
  end
  
  def create
    @chem = Chem.find(params[:chem_id])
    @entering = @chem.enterings.build(entering_params)

    if @entering.save
      flash[:success] = '入庫に成功しました。'
      redirect_to current_user
    else
      flash[:danger] = '入庫に失敗しました。'
      redirect_to current_user
    end
  end
  


 private
  def entering_params
    params.require(:entering).permit(:entering_number, :entering_person)
  end
  
end

app/controllers/historys_controller.rb
class HistorysController < ApplicationController
  def show
    @chem = Chem.find(params[:id])
    @entering = @chem.enterings.all
    @dispatching = @chem.dispatchings.all
    
  end
end

app/controllers/serchings_controller.rb
class SerchingsController < ApplicationController
  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    login_id = params[:session][:login_id]
    password = params[:session][:password]
    if login(login_id, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to @user
    else
      flash[:danger] = 'ログインに失敗しました。'
      redirect_to root_path
    end
  end



  private

  def login(login_id, password)
    @user = User.find_by(login_id: login_id)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @q = @user.chems.search(params[:q])
    @chems = @q.result(distinct: true)
  end

  def new
    @user = User.new
  end
  
  def create
     @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to root_path
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
  end
    
  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end

  
  private

  def user_params
    params.require(:user).permit(:company_name, :login_id, :password, :password_confirmation)
  end
  


end

app/helpers/session_helper.rb
module SessionHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
end

app/views/chems/edit.html.erb
<br>
<br>
<br>
<div class='delete'><%= @chem.chemical_name %>を本当に削除しますか。</div>
<br>
<br>
<br>

<div class='delete2'>
   <%=link_to 'はい', chem_path(@chem.id) , :method => :delete %>
　　&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
   <%=link_to 'いいえ', user_path(current_user) %>
</div>

app/views/chems/new.html.erb
<br>
<br>
<div class='new1'>新規在庫登録</div>
<br>
<div class='new2'>以下より新規薬品を登録下さい。</div>
<br>
<br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@chem) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :chemical_name, '品名' %>
        <%= f.text_field :chemical_name,:placeholder => "薬品名を入力下さい。(20字以内)", class: 'form-control' %>
      </div>
<br>
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/dispatchings/new.html.erb
<br>
<br>
<p class="dispatchings"><%= @chem.chemical_name%>の出庫</p>
<br>
<br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for([@chem,@dispatching]) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :dispatching_number, '出庫数' %>
        <%= f.text_field :dispatching_number,:placeholder => "出庫数を半角数値で入力下さい。(10文字以内)", class: 'form-control' %>
      </div>
<br>
      <div class="form-group">
        <%= f.label :dispatching_person, '出庫者' %>
        <%= f.text_field :dispatching_person,:placeholder => "出庫者を入力下さい。(10文字以内)", class: 'form-control' %>
      </div>
<br> 
<br>
      <%= f.submit '出庫', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/enterings/new.html.erb
<br>
<br>
<p class='enterings'><%= @chem.chemical_name%>の入庫</p>
<br>
<br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for([@chem,@entering]) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :entering_number, '入庫数' %>
        <%= f.text_field :entering_number, :placeholder => "入庫数を半角数値で入力下さい。(10文字以内)",class: 'form-control' %>
      </div>
<br>
      <div class="form-group">
        <%= f.label :entering_person, '入庫者' %>
        <%= f.text_field :entering_person, :placeholder => "入庫者を入力下さい。(10文字以内)",class: 'form-control' %>
      </div>
<br>
<br>
      <%= f.submit '入庫', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/historys/show.html.erb
<br>
<p class="enteringsdiapatchings"><%= @chem.chemical_name %>の入出庫履歴</p>
<br>

<div class="row">

 <div class="col-md-6">
  <p class="enteringshistory">入庫履歴</p>

   <table class="table table-striped table-bordered"> 
    <thead>
     <tr>
      <td class="text-center">日付</th>
      <td class="text-center">入庫数</th>
      <td class="text-center">入庫者</th>
     </tr>
    </thead>

    <tbody class="tbody1">
    <% @entering.each do |entering| %>
     <tr>
      <td><%=entering.created_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %H:%M") %></td>
      <td><%=entering.entering_number %></td>
      <td><%=entering.entering_person %></td>
     </tr>
    <% end %>
   </tbody>
  </table>
 </div>



 <div class="col-md-6">
 <p class="dispatchingshistroy">出庫履歴</p>
  <table class="table table-striped table-bordered"> 
   <thead>
    <tr>
     <td class="text-center">日付</th>
     <td class="text-center">出庫数</th>
     <td class="text-center">出庫者</th>
    </tr>
   </thead>
 
  <tbody class="tbody2">
  <% @dispatching.each do |dispatching| %>
     <tr>
      <td><%=dispatching.created_at.in_time_zone('Tokyo').strftime("%Y/%m/%d %H:%M") %></td>
      <td><%=dispatching.dispatching_number %></td>
      <td><%=dispatching.dispatching_person %></td> 
     </tr>
   <% end %>
  </tbody>
  </table>
 </div>
 
</div>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" >薬品在庫管理システム</a>
      </div>
       <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li><%= link_to '薬品在庫TOP',  user_path(current_user) %></li>
            <li><%= link_to 'ログアウト', logout_path, method: :delete %></li> 
          <% else %>
            <li><%= link_to '新規登録', new_user_path %></li>
            <li><%= link_to 'ログイン', root_path %></li>
        
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>薬品在庫管理システム</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <div class="container">
       <%= render 'layouts/flash_messages' %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/serchings/show.html.erb
<h1>Serchings#show</h1>
<p>Find me in app/views/serchings/show.html.erb</p>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

app/views/toppages/index.html.erb
<br>
<br>
  <div class="one">薬品在庫管理システムへようこそ</div>
<br>
  <div class="two">以下よりログイン下さい。未登録の場合は<%= link_to '新規登録',new_user_path %>をお願い致します。</div>
<br>
<br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(:session, url: sessions_path) do |f| %>

      <div class="form-group">
        <%= f.label :login_id, 'LOG_IN ID' %>
        <%= f.text_field :login_id, :placeholder => "登録したLOG_IN IDを入力下さい。(10字以内)", class: 'form-control' %>
      </div>
<br>
      <div class="form-group">
        <%= f.label :password, 'PASSWORD' %>
        <%= f.password_field :password, :placeholder => "登録したPASSWORDを入力下さい。(10字以内)", class: 'form-control' %>
      </div>
<br>
<br>
      <%= f.submit 'ログイン', class: 'btn btn-primary btn-block' %>
    <% end %>

  </div>
</div>

app/views/users/new.html.erb
<br>
<br>
<div class = signup1>新規登録</div>
<br>
<div class = signup2>以下のフォームに入力して下さい。</div>
<br>
<br>
<div class="row">
  <div class="col-md-6 col-md-offset-3">

    <%= form_for(@user) do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>

      <div class="form-group">
        <%= f.label :company_name, '会社名' %>
        <%= f.text_field :company_name,:placeholder => "登録する会社名を入力下さい。(20字以内)", class: 'form-control' %>
      </div>
<br>
      <div class="form-group">
        <%= f.label :login_id, 'LOG_IN ID' %>
        <%= f.text_field :login_id, :placeholder => "登録するLOG_IN IDを入力下さい。(10字以内)",class: 'form-control' %>
      </div>
<br>
      <div class="form-group">
        <%= f.label :password, 'PASSWORD' %>
        <%= f.password_field :password,:placeholder => "登録するPASSWORDを入力下さい。(10字以内)", class: 'form-control' %>
      </div>
<br>
      <div class="form-group">
        <%= f.label :password_confirmation, 'PASSWORD (確認)' %>
        <%= f.password_field :password_confirmation, :placeholder => "上記で登録したPASSWORDを再入力下さい。(10字以内)", class: 'form-control' %>
      </div>
<br>
<br>
      <%= f.submit '登録', class: 'btn btn-primary btn-block' %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<br>
<br>
<p class='atama'><%= current_user.company_name %>  薬品在庫</p>
<br>
<div class="row">
  <div class="col-md-5">
    
      <%= search_form_for @q, url: user_path(@user)  do |f| %>
        <div class="form-group">
          <div class="col-md-8">
           <%= f.text_field :chemical_name_cont, placeholder: '薬品名を入力下さい。', class:'form-control input-lg' %>
          </div>
          <div class="col-md-2">
           <%= button_tag :type => "submit", :class =>"btn btn-primary btn-lg" do %>
             <i class="glyphicon glyphicon-search"></i>検索
            <% end %>
          </div>
        <% end %>
       </div>
    
  </div>
  <div class="col-md-1">
   <%= link_to '新規在庫登録', new_chem_path, class: "btn btn-success btn-lg" %>
  </div>
</div>
<br>
<div class="row">
<div class="col-md-12 top-margin-20">
<table class="table table-striped table-bordered"> 
 <thead>
  <tr>
    <td class="text-center">品番</th>
    <td class="text-center">在庫数</th>
    <td class="text-center">入庫</th>
    <td class="text-center">出庫</th>
    <td class="text-center">入出履歴</th>
    <td class="text-center">削除</th>    
  </tr>
 </thead>

 <tbody>
 <% @chems.each do |chem| %>
 <tr>
   <td class="text-center"><%=chem.chemical_name %></td>
   <td class="text-center"><%=Chem.find(chem.id).enterings.pluck(:entering_number).sum - Chem.find(chem.id).dispatchings.pluck(:dispatching_number).sum %></td>
   <td class="text-center"><%=link_to '入庫', new_chem_entering_path(chem.id) %></td>
   <td class="text-center"><%=link_to '出庫', new_chem_dispatching_path(chem.id) %></td>
   <td class="text-center"><%=link_to '履歴', history_path(chem.id) %></td>
   <td class="text-center"><%=link_to '削除', edit_chem_path(chem.id) %></td>
 </tr>
<% end %>
 </tbody>
</table>
 </div>
</div>